// <auto-generated />
using System;
using App.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace App.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("App.Domain.Entities.Messages.Message", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MessageContent")
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)");

                    b.Property<short>("MessageStatusId")
                        .HasColumnType("smallint");

                    b.Property<string>("MessageTitle")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("RecipientId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("RecipientName")
                        .HasColumnType("longtext");

                    b.Property<string>("SenderName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("MessageStatusId");

                    b.HasIndex("RecipientId");

                    b.ToTable("message");
                });

            modelBuilder.Entity("App.Domain.Entities.Messages.MessageStatus", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("StatusDescription")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("StatusLabel")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("message_status");
                });

            modelBuilder.Entity("App.Domain.Entities.Messages.MessageSummaryView", b =>
                {
                    b.Property<string>("LatestMessageDetails")
                        .HasColumnType("longtext");

                    b.Property<string>("Receiver")
                        .HasColumnType("longtext");

                    b.Property<string>("Sender")
                        .HasColumnType("longtext");

                    b.ToView("vw_message_summary");
                });

            modelBuilder.Entity("App.Domain.Entities.Messages.Message", b =>
                {
                    b.HasOne("App.Domain.Entities.Messages.MessageStatus", "MessageStatus")
                        .WithMany("MessageItems")
                        .HasForeignKey("MessageStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MessageStatus");
                });

            modelBuilder.Entity("App.Domain.Entities.Messages.MessageStatus", b =>
                {
                    b.Navigation("MessageItems");
                });
#pragma warning restore 612, 618
        }
    }
}
